# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
#export PYENV_ROOT=/root/pyenv
#export PATH="$PYENV_ROOT/bin:$PATH"
#eval "$(pyenv init -)"
